### ISSUE TITLE
Add more algorithm problems!

### ISSUE THREAD

**Issue by domfarolino** [domfarolino/algorithms#2]
## Adding algorithms/datastructures

I have a ton of algorithms and datastructures I'll be committing to this repository over the next few weeks (and years) but if you have anything you'd like to add please do! Algorithms in this repository range from technical interview questions/answers, to online judge problems/solutions, and classic fundamental CS problems.

If it is useful, add whatever you'd like. I only ask that:
- Everything is well documented
- A common language is used (C++, Java, Python, JavaScript, C#, C...)
- and that your commit message has one of the prefixes in the contributing.json file to keep things neat
## Modifications

If you'd like to modify something that already exists in the repository go ahead. Useful changes shouldn't have an issue getting merged.

**Comment by sarsiz** [comment]
Hi, I am interested in helping you with the algos. Can I work on it?

**Comment by domfarolino** [comment]
@sarsiz Sure! If you have an interesting algorithmic problem with a solution, go ahead an post it. Make sure it is well documented. If you need to make a new folder for its category: ex "Graph_Theory" then make this new folder in the algorithm_practice folder, and then for a specific problem make another folder inCamelCasePlease

**Comment by recluse27** [comment]
Hello!
I could help you with algos in C++, Python and JS. Could you just write me the list of algos you need? Do I hame to pull a request to add them? Thanks.

**Comment by DravitLochan** [comment]
I too could write algos in cpp. BST,BFS,DFS, etc. should I go ahead?

**Comment by domfarolino** [comment]
@recluse27 @DravitLochan Thanks for commenting. I have a bunch I'll be committing in the coming days, but I have no specific list of ones that need to be implemented. What I need more than anything would be general graph theory algorithms. I've got BST traversals coming soon so those are covered, but if you'd like to add a `Graph_Theory` folder and some nice graph problems that would be cool. But really anything else you'd want to add, just let me know and if it sounds good you can just submit a PR.

I'm really fine with anything useful. Just make sure you keep your forks [up to date](http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository) for folder hierarchy changes I make

**Comment by DravitLochan** [comment]
On to graph theory.!

**Comment by anuraagbaishya** [comment]
Could help with Python or Java

**Comment by domfarolino** [comment]
@anuraagbaishya Let's go with Java, have any online judge solutions?

**Comment by va6996** [comment]
We could also add AI algorithms and also some path-finding or spanning tree algorithms for graph theory.
Also, I could add some topcoder problem solutions too as I prepare for ICPC.

**Comment by domfarolino** [comment]
@va6996 That sounds perfect! What language are you thinking? Make sure they are well documented ;)

**Comment by va6996** [comment]
c++14 mainly

**Comment by saksham15082** [comment]
Are linear sorting algos needed or just algos involving graphs?

**Comment by anuraagbaishya** [comment]
@domfarolino I have solutions to a few problems I solved on SPOJ and CodeChef. Could add those

**Comment by saksham15082** [comment]
@domfarolino  so what all are permitted solutions to programming questions and algos?

**Comment by saksham15082** [comment]
@domfarolino  also can i submit in C rather than cpp

**Comment by vrush03** [comment]
I can help regarding these ;)..Linked lists and graph theory problems :)

**Comment by hari-sikchi** [comment]
I can help.C++ 14

**Comment by jmeline** [comment]
@domfarolino Are you interested in having Cryptography Algorithms such as Encryption Algorithms

**Comment by domfarolino** [comment]
@jmeline I definitely am

**Comment by TuhinKundu** [comment]
Want to work with either C++ or python. I have solutions of SPOJ, Codechef and HackerRank too. What all need to be modified/added in the repos?

**Comment by domfarolino** [comment]
@TuhinKundu Those problems sound good. I prefer C++ implementations. If an issue revolves around some category that exists in the repository already go ahead and fork this repo, make a new branch, and write a well documented implementation. Check out the contributing file in the root for more info. Make sense?

**Comment by mridulnagpal** [comment]
Hey i am new to open source but i know c++ programming i would like to contribute to this project how can i help??

**Comment by rahul26081995** [comment]
Any programming algorithm or only questions ?

**Comment by pranay-thl** [comment]
@domfarolino Can I contribute few algorithms related to number theory ?

**Comment by domfarolino** [comment]
@pranay-thl absolutely

**Comment by domfarolino** [comment]
@rahul26081995 What do you mean

**Comment by rahul26081995** [comment]
Actually,earlier  i thought we have to add only questions related to algorithms and not just algorithms. So I asked you about that. We can add just an algorithm too right ?

**Comment by domfarolino** [comment]
Every problem you post must have a documented algorithm solution that accompanies it. @rahul26081995

**Comment by rahul26081995** [comment]
Ohk!! Sure 👍
