### ISSUE TITLE
Update datastructure/ Makefiles to compile with debugging symbols

### ISSUE THREAD

**Issue by domfarolino** [domfarolino/algorithms#69]

**Comment by xorz57** [comment]
Can you explain what exactly do you want?

**Comment by domfarolino** [comment]
@xorz57 Basically add the -g flag to the Makefiles each data structure directory of ‘datastructures/‘. Look at the BST Makefile in the BST branch (PR) for reference.

**Comment by xorz57** [comment]
@domfarolino I can also provide a debug and a release mode for every makefile. Additionally, we can wrap all the assertions inside a compiler directive
```c
#ifdef DEBUG
assert(...)
#endif
```

**Comment by domfarolino** [comment]
Shoot it looks like I accidentally fixed the issue myself. I forgot about filing that. I’ll go ahead and close this in a bit :(. Hmm can you explain more about the debug vs release mode? What (beyond assertions) would this provide?

I ask because I’m not sure I’m crazy about the compiler directives scattered about.

**Comment by xorz57** [comment]
@domfarolino What I am talking about is I can make your Makefiles build faster and provide 2 build modes (Release / Debug). Release mode will provide executables with all compiler optimizations on, while Debug mode will enable assertions and compile code as is without any optimizations. If you want me to take care of this let me know.

**Comment by xorz57** [comment]
@domfarolino + By the time most of your code is in C++ we could use the [Catch Testing Framework](https://github.com/philsquared/Catch) for Unit Tests. But this is offtopic.

**Comment by domfarolino** [comment]
I'd personally say the testing framework (instead of my homemade sketchy tests) is a bigger priority and something I'm more interested in. Plus this framework sounds easier to use than CXXTest it seems. Interested in submitting an initial PR and working on it with me?

**Comment by xorz57** [comment]
@domfarolino Yes I am in.

**Comment by xorz57** [comment]
@domfarolino I opened a pull request.
