### ISSUE TITLE
Briefly document BST traversal algorithms

### ISSUE THREAD

**Issue by domfarolino** [domfarolino/algorithms#73]
See `src/datastructures/BST/README.md`

**Comment by sahilbansal17** [comment]
can you please elaborate, what exactly needs to be done ?

**Comment by domfarolino** [comment]
Yeah so basically at the [end](https://github.com/domfarolino/algorithms/tree/master/src/datastructures/BST#traversals) of the file there is an empty section for all of the traversals (pre/post/in-order) and it would be nice to have some accompanying documentation for them i.e., explaining what the traversals do, how they work, what output they produce etc. Does that make sense?
